
(defpackage #:cl-glfw-opengl-ext_coordinate_frame-system (:use #:asdf #:cl)) 
(in-package #:cl-glfw-opengl-ext_coordinate_frame-system) 
(defsystem cl-glfw-opengl-ext_coordinate_frame :description
 "cl-glfw's cl-glfw-opengl-ext_coordinate_frame Binding" :author
 "Generated by cl-glfw's /home/bill/programming/cl-glfw/generators/make-bindings-from-spec.lisp"
 :license "Public Domain" :depends-on (cl-glfw) :components
 ((:module lib :components ((:file "opengl-ext_coordinate_frame"))))) 