
(defpackage #:cl-glfw-opengl-sgis_texture4d-system (:use #:asdf #:cl)) 
(in-package #:cl-glfw-opengl-sgis_texture4d-system) 
(defsystem "cl-glfw-opengl-sgis_texture4d" :description
 "cl-glfw's cl-glfw-opengl-sgis_texture4d Binding" :author
 "Generated by cl-glfw's /home/bill/programming/cl-glfw/generators/make-bindings-from-spec.lisp"
 :license "Public Domain" :depends-on ("cl-glfw") :components
 ((:module "lib" :components ((:file "opengl-sgis_texture4d"))))) 