
(defpackage #:cl-glfw-opengl-ati_vertex_streams-system (:use #:asdf #:cl)) 
(in-package #:cl-glfw-opengl-ati_vertex_streams-system) 
(defsystem "cl-glfw-opengl-ati_vertex_streams" :description
 "cl-glfw's cl-glfw-opengl-ati_vertex_streams Binding" :author
 "Generated by cl-glfw's /home/bill/programming/cl-glfw/generators/make-bindings-from-spec.lisp"
 :license "Public Domain" :depends-on ("cl-glfw") :components
 ((:module "lib" :components ((:file "opengl-ati_vertex_streams"))))) 