
(defpackage #:cl-glfw-opengl-sgix_pixel_texture-system (:use #:asdf #:cl)) 
(in-package #:cl-glfw-opengl-sgix_pixel_texture-system) 
(defsystem cl-glfw-opengl-sgix_pixel_texture :description
 "cl-glfw's cl-glfw-opengl-sgix_pixel_texture Binding" :author
 "Generated by cl-glfw's /home/bill/programming/cl-glfw/generators/make-bindings-from-spec.lisp"
 :license "Public Domain" :depends-on (cl-glfw) :components
 ((:module lib :components ((:file "opengl-sgix_pixel_texture"))))) 