
(defpackage #:cl-glfw-opengl-sun_triangle_list-system (:use #:asdf #:cl)) 
(in-package #:cl-glfw-opengl-sun_triangle_list-system) 
(defsystem cl-glfw-opengl-sun_triangle_list :description
 "cl-glfw's cl-glfw-opengl-sun_triangle_list Binding" :author
 "Generated by cl-glfw's /home/bill/programming/cl-glfw/generators/make-bindings-from-spec.lisp"
 :license "Public Domain" :depends-on (cl-glfw) :components
 ((:module lib :components ((:file "opengl-sun_triangle_list"))))) 