
(defpackage #:cl-glfw-opengl-mesa_resize_buffers-system (:use #:asdf #:cl)) 
(in-package #:cl-glfw-opengl-mesa_resize_buffers-system) 
(defsystem "cl-glfw-opengl-mesa_resize_buffers" :description
 "cl-glfw's cl-glfw-opengl-mesa_resize_buffers Binding" :author
 "Generated by cl-glfw's /home/bill/programming/cl-glfw/generators/make-bindings-from-spec.lisp"
 :license "Public Domain" :depends-on ("cl-glfw") :components
 ((:module "lib" :components ((:file "opengl-mesa_resize_buffers"))))) 