;;;; This file was automatically generated by nil

(defpackage #:cl-glfw-opengl-ibm_vertex_array_lists-system (:use #:asdf #:cl)) 
(in-package #:cl-glfw-opengl-ibm_vertex_array_lists-system) 
(defsystem cl-glfw-opengl-ibm_vertex_array_lists :description
 "cl-glfw's ibm_vertex_array_lists binding" :author
 "Generated by cl-glfw's nil" :licence "Public Domain" :depends-on
 (cl-glfw-opengl) :components ((:file "opengl-ibm_vertex_array_lists"))) 