;;;; This file was automatically generated by nil

(defpackage #:cl-glfw-opengl-ext_color_subtable-system (:use #:asdf #:cl)) 
(in-package #:cl-glfw-opengl-ext_color_subtable-system) 
(defsystem cl-glfw-opengl-ext_color_subtable :description
 "cl-glfw's ext_color_subtable binding" :author "Generated by cl-glfw's nil"
 :licence "Public Domain" :depends-on (cl-glfw-opengl) :components
 ((:file "opengl-ext_color_subtable"))) 