;;;; This file was automatically generated by /home/bill/programming/cl-glfw/generators/make-bindings-from-spec.lisp

(defpackage #:cl-glfw-opengl-arb_texture_rgb10_a2ui-system
  (:use #:asdf #:cl)) 
(in-package #:cl-glfw-opengl-arb_texture_rgb10_a2ui-system) 
(defsystem cl-glfw-opengl-arb_texture_rgb10_a2ui :description
 "cl-glfw's arb_texture_rgb10_a2ui binding" :author
 "Generated by cl-glfw's /home/bill/programming/cl-glfw/generators/make-bindings-from-spec.lisp"
 :licence "Public Domain" :depends-on (cl-glfw-opengl-core) :components
 ((:file "opengl-arb_texture_rgb10_a2ui"))) 
