;;;; This file was automatically generated by /home/bill/programming/cl-glfw/generators/make-bindings-from-spec.lisp

(defpackage #:cl-glfw-opengl-ati_text_fragment_shader-system
  (:use #:asdf #:cl)) 
(in-package #:cl-glfw-opengl-ati_text_fragment_shader-system) 
(defsystem cl-glfw-opengl-ati_text_fragment_shader :description
 "cl-glfw's ati_text_fragment_shader binding" :author
 "Generated by cl-glfw's /home/bill/programming/cl-glfw/generators/make-bindings-from-spec.lisp"
 :licence "Public Domain" :depends-on (cl-glfw-opengl-core) :components
 ((:file "opengl-ati_text_fragment_shader"))) 
