;;;; This file was automatically generated by /home/bill/programming/cl-glfw/generators/make-bindings-from-spec.lisp

(defpackage #:cl-glfw-opengl-arb_robustness-system
  (:use #:asdf #:cl)) 
(in-package #:cl-glfw-opengl-arb_robustness-system) 
(defsystem cl-glfw-opengl-arb_robustness :description
 "cl-glfw's arb_robustness binding" :author
 "Generated by cl-glfw's /home/bill/programming/cl-glfw/generators/make-bindings-from-spec.lisp"
 :licence "Public Domain" :depends-on (cl-glfw-opengl-core) :components
 ((:file "opengl-arb_robustness"))) 
