;;;; This file was automatically generated by nil

(defpackage #:cl-glfw-opengl-nv_primitive_restart-system (:use #:asdf #:cl)) 
(in-package #:cl-glfw-opengl-nv_primitive_restart-system) 
(defsystem cl-glfw-opengl-nv_primitive_restart :description
 "cl-glfw's nv_primitive_restart binding" :author "Generated by cl-glfw's nil"
 :licence "Public Domain" :depends-on (cl-glfw-opengl) :components
 ((:file "opengl-nv_primitive_restart"))) 