;;;; This file was automatically generated by nil

(defpackage #:cl-glfw-opengl-apple_fence-system (:use #:asdf #:cl)) 
(in-package #:cl-glfw-opengl-apple_fence-system) 
(defsystem cl-glfw-opengl-apple_fence :description
 "cl-glfw's apple_fence binding" :author "Generated by cl-glfw's nil" :licence
 "Public Domain" :depends-on (cl-glfw-opengl) :components
 ((:file "opengl-apple_fence"))) 