
(defpackage #:cl-glfw-opengl-arb_texture_compression-system (:use #:asdf #:cl)) 
(in-package #:cl-glfw-opengl-arb_texture_compression-system) 
(defsystem cl-glfw-opengl-arb_texture_compression :description
 "cl-glfw's cl-glfw-opengl-arb_texture_compression Binding" :author
 "Generated by cl-glfw's /home/bill/programming/cl-glfw/generators/make-bindings-from-spec.lisp"
 :licence "Public Domain" :depends-on (cl-glfw-opengl) :components
 ((:file "opengl-arb_texture_compression"))) 