
(defpackage #:cl-glfw-opengl-arb_vertex_shader-system (:use #:asdf #:cl)) 
(in-package #:cl-glfw-opengl-arb_vertex_shader-system) 
(defsystem cl-glfw-opengl-arb_vertex_shader :description
 "cl-glfw's cl-glfw-opengl-arb_vertex_shader Binding" :author
 "Generated by cl-glfw's /home/bill/programming/cl-glfw/generators/make-bindings-from-spec.lisp"
 :license "Public Domain" :depends-on (cl-glfw) :components
 ((:module lib :components ((:file "opengl-arb_vertex_shader"))))) 