;;;; This file was automatically generated by nil

(defpackage #:cl-glfw-opengl-ext_framebuffer_blit-system (:use #:asdf #:cl)) 
(in-package #:cl-glfw-opengl-ext_framebuffer_blit-system) 
(defsystem cl-glfw-opengl-ext_framebuffer_blit :description
 "cl-glfw's ext_framebuffer_blit binding" :author "Generated by cl-glfw's nil"
 :licence "Public Domain" :depends-on (cl-glfw-opengl) :components
 ((:file "opengl-ext_framebuffer_blit"))) 