;;;; This file was automatically generated by nil

(defpackage #:cl-glfw-opengl-nv_register_combiners-system (:use #:asdf #:cl)) 
(in-package #:cl-glfw-opengl-nv_register_combiners-system) 
(defsystem cl-glfw-opengl-nv_register_combiners :description
 "cl-glfw's nv_register_combiners binding" :author "Generated by cl-glfw's nil"
 :licence "Public Domain" :depends-on (cl-glfw-opengl) :components
 ((:file "opengl-nv_register_combiners"))) 