;;;; This file was automatically generated by nil

(defpackage #:cl-glfw-opengl-sgix_fragment_lighting-system (:use #:asdf #:cl)) 
(in-package #:cl-glfw-opengl-sgix_fragment_lighting-system) 
(defsystem cl-glfw-opengl-sgix_fragment_lighting :description
 "cl-glfw's sgix_fragment_lighting binding" :author
 "Generated by cl-glfw's nil" :licence "Public Domain" :depends-on
 (cl-glfw-opengl) :components ((:file "opengl-sgix_fragment_lighting"))) 