;;;; This file was automatically generated by nil

(defpackage #:cl-glfw-opengl-nv_fence-system (:use #:asdf #:cl)) 
(in-package #:cl-glfw-opengl-nv_fence-system) 
(defsystem cl-glfw-opengl-nv_fence :description "cl-glfw's nv_fence binding"
 :author "Generated by cl-glfw's nil" :licence "Public Domain" :depends-on
 (cl-glfw-opengl) :components ((:file "opengl-nv_fence"))) 