;;;; This file was automatically generated by /home/bill/programming/cl-glfw/generators/make-bindings-from-spec.lisp

(defpackage #:cl-glfw-opengl-amd_performance_monitor-system
  (:use #:asdf #:cl)) 
(in-package #:cl-glfw-opengl-amd_performance_monitor-system) 
(defsystem cl-glfw-opengl-amd_performance_monitor :description
 "cl-glfw's amd_performance_monitor binding" :author
 "Generated by cl-glfw's /home/bill/programming/cl-glfw/generators/make-bindings-from-spec.lisp"
 :licence "Public Domain" :depends-on (cl-glfw-opengl-core) :components
 ((:file "opengl-amd_performance_monitor"))) 
