;;;; This file was automatically generated by nil

(defpackage #:cl-glfw-opengl-arb_window_pos-system (:use #:asdf #:cl)) 
(in-package #:cl-glfw-opengl-arb_window_pos-system) 
(defsystem cl-glfw-opengl-arb_window_pos :description
 "cl-glfw's arb_window_pos binding" :author "Generated by cl-glfw's nil"
 :licence "Public Domain" :depends-on (cl-glfw-opengl) :components
 ((:file "opengl-arb_window_pos"))) 