;;;; This file was automatically generated by /home/bill/programming/cl-glfw/generators/make-bindings-from-spec.lisp

(defpackage #:cl-glfw-opengl-sgix_tag_sample_buffer-system (:use #:asdf #:cl)) 
(in-package #:cl-glfw-opengl-sgix_tag_sample_buffer-system) 
(defsystem cl-glfw-opengl-sgix_tag_sample_buffer :description
 "cl-glfw's cl-glfw-opengl-sgix_tag_sample_buffer Binding" :author
 "Generated by cl-glfw's /home/bill/programming/cl-glfw/generators/make-bindings-from-spec.lisp"
 :licence "Public Domain" :depends-on (cl-glfw-opengl) :components
 ((:file "opengl-sgix_tag_sample_buffer"))) 