
(defpackage #:cl-glfw-opengl-ibm_vertex_array_lists-system (:use #:asdf #:cl)) 
(in-package #:cl-glfw-opengl-ibm_vertex_array_lists-system) 
(defsystem cl-glfw-opengl-ibm_vertex_array_lists :description
 "cl-glfw's cl-glfw-opengl-ibm_vertex_array_lists Binding" :author
 "Generated by cl-glfw's /home/bill/programming/cl-glfw/generators/make-bindings-from-spec.lisp"
 :license "Public Domain" :depends-on (cl-glfw) :components
 ((:module lib :components ((:file "opengl-ibm_vertex_array_lists"))))) 