
(defpackage #:cl-glfw-opengl-nv_fragment_program-system (:use #:asdf #:cl)) 
(in-package #:cl-glfw-opengl-nv_fragment_program-system) 
(defsystem cl-glfw-opengl-nv_fragment_program :description
 "cl-glfw's cl-glfw-opengl-nv_fragment_program Binding" :author
 "Generated by cl-glfw's /home/bill/programming/cl-glfw/generators/make-bindings-from-spec.lisp"
 :licence "Public Domain" :depends-on (cl-glfw-opengl) :components
 ((:file "opengl-nv_fragment_program"))) 