;;;; This file was automatically generated by nil

(defpackage #:cl-glfw-opengl-sgix_polynomial_ffd-system (:use #:asdf #:cl)) 
(in-package #:cl-glfw-opengl-sgix_polynomial_ffd-system) 
(defsystem cl-glfw-opengl-sgix_polynomial_ffd :description
 "cl-glfw's sgix_polynomial_ffd binding" :author "Generated by cl-glfw's nil"
 :licence "Public Domain" :depends-on (cl-glfw-opengl) :components
 ((:file "opengl-sgix_polynomial_ffd"))) 