;;;; This file was automatically generated by nil

(defpackage #:cl-glfw-opengl-ext_draw_instanced-system (:use #:asdf #:cl)) 
(in-package #:cl-glfw-opengl-ext_draw_instanced-system) 
(defsystem cl-glfw-opengl-ext_draw_instanced :description
 "cl-glfw's ext_draw_instanced binding" :author "Generated by cl-glfw's nil"
 :licence "Public Domain" :depends-on (cl-glfw-opengl) :components
 ((:file "opengl-ext_draw_instanced"))) 