;;;; This file was automatically generated by nil

(defpackage #:cl-glfw-opengl-ext_compiled_vertex_array-system
            (:use #:asdf #:cl)) 
(in-package #:cl-glfw-opengl-ext_compiled_vertex_array-system) 
(defsystem cl-glfw-opengl-ext_compiled_vertex_array :description
 "cl-glfw's ext_compiled_vertex_array binding" :author
 "Generated by cl-glfw's nil" :licence "Public Domain" :depends-on
 (cl-glfw-opengl) :components ((:file "opengl-ext_compiled_vertex_array"))) 