;;;; This file was automatically generated by /home/bill/programming/cl-glfw/generators/make-bindings-from-spec.lisp

(defpackage #:cl-glfw-opengl-arb_point_sprite-system
  (:use #:asdf #:cl)) 
(in-package #:cl-glfw-opengl-arb_point_sprite-system) 
(defsystem cl-glfw-opengl-arb_point_sprite :description
 "cl-glfw's arb_point_sprite binding" :author
 "Generated by cl-glfw's /home/bill/programming/cl-glfw/generators/make-bindings-from-spec.lisp"
 :licence "Public Domain" :depends-on (cl-glfw-opengl-core) :components
 ((:file "opengl-arb_point_sprite"))) 
