;;;; This file was automatically generated by /home/bill/programming/cl-glfw/generators/make-bindings-from-spec.lisp

(defpackage #:cl-glfw-opengl-gremedy_string_marker-system
  (:use #:asdf #:cl)) 
(in-package #:cl-glfw-opengl-gremedy_string_marker-system) 
(defsystem cl-glfw-opengl-gremedy_string_marker :description
 "cl-glfw's gremedy_string_marker binding" :author
 "Generated by cl-glfw's /home/bill/programming/cl-glfw/generators/make-bindings-from-spec.lisp"
 :licence "Public Domain" :depends-on (cl-glfw-opengl-core) :components
 ((:file "opengl-gremedy_string_marker"))) 
