;;;; This file was automatically generated by nil

(defpackage #:cl-glfw-opengl-sgix_reference_plane-system (:use #:asdf #:cl)) 
(in-package #:cl-glfw-opengl-sgix_reference_plane-system) 
(defsystem cl-glfw-opengl-sgix_reference_plane :description
 "cl-glfw's sgix_reference_plane binding" :author "Generated by cl-glfw's nil"
 :licence "Public Domain" :depends-on (cl-glfw-opengl) :components
 ((:file "opengl-sgix_reference_plane"))) 