;;;; This file was automatically generated by nil

(defpackage #:cl-glfw-opengl-ingr_blend_func_separate-system (:use #:asdf #:cl)) 
(in-package #:cl-glfw-opengl-ingr_blend_func_separate-system) 
(defsystem cl-glfw-opengl-ingr_blend_func_separate :description
 "cl-glfw's ingr_blend_func_separate binding" :author
 "Generated by cl-glfw's nil" :licence "Public Domain" :depends-on
 (cl-glfw-opengl) :components ((:file "opengl-ingr_blend_func_separate"))) 