;;;; This file was automatically generated by /home/bill/programming/cl-glfw/generators/make-bindings-from-spec.lisp

(defpackage #:cl-glfw-opengl-nv_vertex_array_range2-system
  (:use #:asdf #:cl)) 
(in-package #:cl-glfw-opengl-nv_vertex_array_range2-system) 
(defsystem cl-glfw-opengl-nv_vertex_array_range2 :description
 "cl-glfw's nv_vertex_array_range2 binding" :author
 "Generated by cl-glfw's /home/bill/programming/cl-glfw/generators/make-bindings-from-spec.lisp"
 :licence "Public Domain" :depends-on (cl-glfw-opengl-core) :components
 ((:file "opengl-nv_vertex_array_range2"))) 
