
(defpackage #:cl-glfw-opengl-ati_map_object_buffer-system (:use #:asdf #:cl)) 
(in-package #:cl-glfw-opengl-ati_map_object_buffer-system) 
(defsystem cl-glfw-opengl-ati_map_object_buffer :description
 "cl-glfw's cl-glfw-opengl-ati_map_object_buffer Binding" :author
 "Generated by cl-glfw's /home/bill/programming/cl-glfw/generators/make-bindings-from-spec.lisp"
 :license "Public Domain" :depends-on (cl-glfw) :components
 ((:module lib :components ((:file "opengl-ati_map_object_buffer"))))) 