;;;; This file was automatically generated by nil

(defpackage #:cl-glfw-opengl-ext_gpu_shader4-system (:use #:asdf #:cl)) 
(in-package #:cl-glfw-opengl-ext_gpu_shader4-system) 
(defsystem cl-glfw-opengl-ext_gpu_shader4 :description
 "cl-glfw's ext_gpu_shader4 binding" :author "Generated by cl-glfw's nil"
 :licence "Public Domain" :depends-on (cl-glfw-opengl) :components
 ((:file "opengl-ext_gpu_shader4"))) 