;;;; This file was automatically generated by /home/bill/programming/cl-glfw/generators/make-bindings-from-spec.lisp

(defpackage #:cl-glfw-opengl-ext_stencil_clear_tag-system
  (:use #:asdf #:cl)) 
(in-package #:cl-glfw-opengl-ext_stencil_clear_tag-system) 
(defsystem cl-glfw-opengl-ext_stencil_clear_tag :description
 "cl-glfw's ext_stencil_clear_tag binding" :author
 "Generated by cl-glfw's /home/bill/programming/cl-glfw/generators/make-bindings-from-spec.lisp"
 :licence "Public Domain" :depends-on (cl-glfw-opengl-core) :components
 ((:file "opengl-ext_stencil_clear_tag"))) 
