
(defpackage #:cl-glfw-opengl-ati_separate_stencil-system (:use #:asdf #:cl)) 
(in-package #:cl-glfw-opengl-ati_separate_stencil-system) 
(defsystem cl-glfw-opengl-ati_separate_stencil :description
 "cl-glfw's cl-glfw-opengl-ati_separate_stencil Binding" :author
 "Generated by cl-glfw's /home/bill/programming/cl-glfw/generators/make-bindings-from-spec.lisp"
 :license "Public Domain" :depends-on (cl-glfw) :components
 ((:file "opengl-ati_separate_stencil"))) 