
(defpackage #:cl-glfw-opengl-ext_vertex_weighting-system (:use #:asdf #:cl)) 
(in-package #:cl-glfw-opengl-ext_vertex_weighting-system) 
(defsystem cl-glfw-opengl-ext_vertex_weighting :description
 "cl-glfw's cl-glfw-opengl-ext_vertex_weighting Binding" :author
 "Generated by cl-glfw's /home/bill/programming/cl-glfw/generators/make-bindings-from-spec.lisp"
 :license "Public Domain" :depends-on (cl-glfw) :components
 ((:file "opengl-ext_vertex_weighting"))) 