;;;; This file was automatically generated by nil

(defpackage #:cl-glfw-opengl-sgis_detail_texture-system (:use #:asdf #:cl)) 
(in-package #:cl-glfw-opengl-sgis_detail_texture-system) 
(defsystem cl-glfw-opengl-sgis_detail_texture :description
 "cl-glfw's sgis_detail_texture binding" :author "Generated by cl-glfw's nil"
 :licence "Public Domain" :depends-on (cl-glfw-opengl) :components
 ((:file "opengl-sgis_detail_texture"))) 