;;;; This file was automatically generated by nil

(defpackage #:cl-glfw-opengl-gremedy_string_marker-system (:use #:asdf #:cl)) 
(in-package #:cl-glfw-opengl-gremedy_string_marker-system) 
(defsystem cl-glfw-opengl-gremedy_string_marker :description
 "cl-glfw's gremedy_string_marker binding" :author "Generated by cl-glfw's nil"
 :licence "Public Domain" :depends-on (cl-glfw-opengl) :components
 ((:file "opengl-gremedy_string_marker"))) 