
(defpackage #:cl-glfw-opengl-version_1_3-system (:use #:asdf #:cl)) 
(in-package #:cl-glfw-opengl-version_1_3-system) 
(defsystem cl-glfw-opengl-version_1_3 :description
 "cl-glfw's cl-glfw-opengl-version_1_3 Binding" :author
 "Generated by cl-glfw's /home/bill/programming/cl-glfw/generators/make-bindings-from-spec.lisp"
 :license "Public Domain" :depends-on (cl-glfw |cl-glfw-opengl-version_1_2|)
 :components ((:file "opengl-version_1_3"))) 