;;;; This file was automatically generated by nil

(defpackage #:cl-glfw-opengl-hp_image_transform-system (:use #:asdf #:cl)) 
(in-package #:cl-glfw-opengl-hp_image_transform-system) 
(defsystem cl-glfw-opengl-hp_image_transform :description
 "cl-glfw's hp_image_transform binding" :author "Generated by cl-glfw's nil"
 :licence "Public Domain" :depends-on (cl-glfw-opengl) :components
 ((:file "opengl-hp_image_transform"))) 