;;;; This file was automatically generated by /home/bill/programming/cl-glfw/generators/make-bindings-from-spec.lisp

(defpackage #:cl-glfw-opengl-sgix_texture_coordinate_clamp-system
  (:use #:asdf #:cl)) 
(in-package #:cl-glfw-opengl-sgix_texture_coordinate_clamp-system) 
(defsystem cl-glfw-opengl-sgix_texture_coordinate_clamp :description
 "cl-glfw's sgix_texture_coordinate_clamp binding" :author
 "Generated by cl-glfw's /home/bill/programming/cl-glfw/generators/make-bindings-from-spec.lisp"
 :licence "Public Domain" :depends-on (cl-glfw-opengl-core) :components
 ((:file "opengl-sgix_texture_coordinate_clamp"))) 
