;;;; This file was automatically generated by /home/bill/programming/cl-glfw/generators/make-bindings-from-spec.lisp

(defpackage #:cl-glfw-opengl-apple_texture_range-system
  (:use #:asdf #:cl)) 
(in-package #:cl-glfw-opengl-apple_texture_range-system) 
(defsystem cl-glfw-opengl-apple_texture_range :description
 "cl-glfw's apple_texture_range binding" :author
 "Generated by cl-glfw's /home/bill/programming/cl-glfw/generators/make-bindings-from-spec.lisp"
 :licence "Public Domain" :depends-on (cl-glfw-opengl-core) :components
 ((:file "opengl-apple_texture_range"))) 
