;;;; This file was automatically generated by nil

(defpackage #:cl-glfw-opengl-ati_element_array-system (:use #:asdf #:cl)) 
(in-package #:cl-glfw-opengl-ati_element_array-system) 
(defsystem cl-glfw-opengl-ati_element_array :description
 "cl-glfw's ati_element_array binding" :author "Generated by cl-glfw's nil"
 :licence "Public Domain" :depends-on (cl-glfw-opengl) :components
 ((:file "opengl-ati_element_array"))) 