;;;; This file was automatically generated by /home/bill/programming/cl-glfw/generators/make-bindings-from-spec.lisp

(defpackage #:cl-glfw-opengl-mesax_texture_stack-system
  (:use #:asdf #:cl)) 
(in-package #:cl-glfw-opengl-mesax_texture_stack-system) 
(defsystem cl-glfw-opengl-mesax_texture_stack :description
 "cl-glfw's mesax_texture_stack binding" :author
 "Generated by cl-glfw's /home/bill/programming/cl-glfw/generators/make-bindings-from-spec.lisp"
 :licence "Public Domain" :depends-on (cl-glfw-opengl-core) :components
 ((:file "opengl-mesax_texture_stack"))) 
