;;;; This file was automatically generated by nil

(defpackage #:cl-glfw-opengl-sun_vertex-system (:use #:asdf #:cl)) 
(in-package #:cl-glfw-opengl-sun_vertex-system) 
(defsystem cl-glfw-opengl-sun_vertex :description
 "cl-glfw's sun_vertex binding" :author "Generated by cl-glfw's nil" :licence
 "Public Domain" :depends-on (cl-glfw-opengl) :components
 ((:file "opengl-sun_vertex"))) 