;;;; This file was automatically generated by nil

(defpackage #:cl-glfw-opengl-sgi_color_table-system (:use #:asdf #:cl)) 
(in-package #:cl-glfw-opengl-sgi_color_table-system) 
(defsystem cl-glfw-opengl-sgi_color_table :description
 "cl-glfw's sgi_color_table binding" :author "Generated by cl-glfw's nil"
 :licence "Public Domain" :depends-on (cl-glfw-opengl) :components
 ((:file "opengl-sgi_color_table"))) 