
(defpackage #:cl-glfw-opengl-hp_image_transform-system (:use #:asdf #:cl)) 
(in-package #:cl-glfw-opengl-hp_image_transform-system) 
(defsystem cl-glfw-opengl-hp_image_transform :description
 "cl-glfw's cl-glfw-opengl-hp_image_transform Binding" :author
 "Generated by cl-glfw's /home/bill/programming/cl-glfw/generators/make-bindings-from-spec.lisp"
 :licence "Public Domain" :depends-on (cl-glfw-opengl) :components
 ((:file "opengl-hp_image_transform"))) 