;;;; This file was automatically generated by nil

(defpackage #:cl-glfw-opengl-ext_texture_integer-system (:use #:asdf #:cl)) 
(in-package #:cl-glfw-opengl-ext_texture_integer-system) 
(defsystem cl-glfw-opengl-ext_texture_integer :description
 "cl-glfw's ext_texture_integer binding" :author "Generated by cl-glfw's nil"
 :licence "Public Domain" :depends-on (cl-glfw-opengl) :components
 ((:file "opengl-ext_texture_integer"))) 