;;;; This file was automatically generated by /home/bill/programming/cl-glfw/generators/make-bindings-from-spec.lisp

(defpackage #:cl-glfw-opengl-sgix_line_quality_hint-system
  (:use #:asdf #:cl)) 
(in-package #:cl-glfw-opengl-sgix_line_quality_hint-system) 
(defsystem cl-glfw-opengl-sgix_line_quality_hint :description
 "cl-glfw's sgix_line_quality_hint binding" :author
 "Generated by cl-glfw's /home/bill/programming/cl-glfw/generators/make-bindings-from-spec.lisp"
 :licence "Public Domain" :depends-on (cl-glfw-opengl-core) :components
 ((:file "opengl-sgix_line_quality_hint"))) 
