;;;; This file was automatically generated by /home/bill/programming/cl-glfw/generators/make-bindings-from-spec.lisp

(defpackage #:cl-glfw-opengl-ext_x11_sync_object-system
  (:use #:asdf #:cl)) 
(in-package #:cl-glfw-opengl-ext_x11_sync_object-system) 
(defsystem cl-glfw-opengl-ext_x11_sync_object :description
 "cl-glfw's ext_x11_sync_object binding" :author
 "Generated by cl-glfw's /home/bill/programming/cl-glfw/generators/make-bindings-from-spec.lisp"
 :licence "Public Domain" :depends-on (cl-glfw-opengl-core) :components
 ((:file "opengl-ext_x11_sync_object"))) 
