;;;; This file was automatically generated by nil

(defpackage #:cl-glfw-opengl-ext_multi_draw_arrays-system (:use #:asdf #:cl)) 
(in-package #:cl-glfw-opengl-ext_multi_draw_arrays-system) 
(defsystem cl-glfw-opengl-ext_multi_draw_arrays :description
 "cl-glfw's ext_multi_draw_arrays binding" :author "Generated by cl-glfw's nil"
 :licence "Public Domain" :depends-on (cl-glfw-opengl) :components
 ((:file "opengl-ext_multi_draw_arrays"))) 