
(defpackage #:cl-glfw-opengl-nv_evaluators-system (:use #:asdf #:cl)) 
(in-package #:cl-glfw-opengl-nv_evaluators-system) 
(defsystem cl-glfw-opengl-nv_evaluators :description
 "cl-glfw's cl-glfw-opengl-nv_evaluators Binding" :author
 "Generated by cl-glfw's /home/bill/programming/cl-glfw/generators/make-bindings-from-spec.lisp"
 :licence "Public Domain" :depends-on (cl-glfw-opengl) :components
 ((:file "opengl-nv_evaluators"))) 