
(defpackage #:cl-glfw-opengl-3dfx_tbuffer-system (:use #:asdf #:cl)) 
(in-package #:cl-glfw-opengl-3dfx_tbuffer-system) 
(defsystem cl-glfw-opengl-3dfx_tbuffer :description
 "cl-glfw's cl-glfw-opengl-3dfx_tbuffer Binding" :author
 "Generated by cl-glfw's /home/bill/programming/cl-glfw/generators/make-bindings-from-spec.lisp"
 :license "Public Domain" :depends-on (cl-glfw) :components
 ((:file "opengl-3dfx_tbuffer"))) 