;;;; This file was automatically generated by nil

(defpackage #:cl-glfw-opengl-3dfx_tbuffer-system (:use #:asdf #:cl)) 
(in-package #:cl-glfw-opengl-3dfx_tbuffer-system) 
(defsystem cl-glfw-opengl-3dfx_tbuffer :description
 "cl-glfw's 3dfx_tbuffer binding" :author "Generated by cl-glfw's nil" :licence
 "Public Domain" :depends-on (cl-glfw-opengl) :components
 ((:file "opengl-3dfx_tbuffer"))) 