;;;; This file was automatically generated by /home/bill/programming/cl-glfw/generators/make-bindings-from-spec.lisp

(defpackage #:cl-glfw-opengl-sun_global_alpha-system
  (:use #:asdf #:cl)) 
(in-package #:cl-glfw-opengl-sun_global_alpha-system) 
(defsystem cl-glfw-opengl-sun_global_alpha :description
 "cl-glfw's sun_global_alpha binding" :author
 "Generated by cl-glfw's /home/bill/programming/cl-glfw/generators/make-bindings-from-spec.lisp"
 :licence "Public Domain" :depends-on (cl-glfw-opengl-core) :components
 ((:file "opengl-sun_global_alpha"))) 
