
(defpackage #:cl-glfw-opengl-ext_framebuffer_multisample-system
            (:use #:asdf #:cl)) 
(in-package #:cl-glfw-opengl-ext_framebuffer_multisample-system) 
(defsystem cl-glfw-opengl-ext_framebuffer_multisample :description
 "cl-glfw's cl-glfw-opengl-ext_framebuffer_multisample Binding" :author
 "Generated by cl-glfw's /home/bill/programming/cl-glfw/generators/make-bindings-from-spec.lisp"
 :licence "Public Domain" :depends-on (cl-glfw-opengl) :components
 ((:file "opengl-ext_framebuffer_multisample"))) 