;;;; This file was automatically generated by /home/bill/programming/cl-glfw/generators/make-bindings-from-spec.lisp

(defpackage #:cl-glfw-opengl-oml_subsample-system
  (:use #:asdf #:cl)) 
(in-package #:cl-glfw-opengl-oml_subsample-system) 
(defsystem cl-glfw-opengl-oml_subsample :description
 "cl-glfw's oml_subsample binding" :author
 "Generated by cl-glfw's /home/bill/programming/cl-glfw/generators/make-bindings-from-spec.lisp"
 :licence "Public Domain" :depends-on (cl-glfw-opengl-core) :components
 ((:file "opengl-oml_subsample"))) 
