;;;; This file was automatically generated by nil

(defpackage #:cl-glfw-opengl-sgis_fog_function-system (:use #:asdf #:cl)) 
(in-package #:cl-glfw-opengl-sgis_fog_function-system) 
(defsystem cl-glfw-opengl-sgis_fog_function :description
 "cl-glfw's sgis_fog_function binding" :author "Generated by cl-glfw's nil"
 :licence "Public Domain" :depends-on (cl-glfw-opengl) :components
 ((:file "opengl-sgis_fog_function"))) 