;;;; This file was automatically generated by nil

(defpackage #:cl-glfw-opengl-ati_envmap_bumpmap-system (:use #:asdf #:cl)) 
(in-package #:cl-glfw-opengl-ati_envmap_bumpmap-system) 
(defsystem cl-glfw-opengl-ati_envmap_bumpmap :description
 "cl-glfw's ati_envmap_bumpmap binding" :author "Generated by cl-glfw's nil"
 :licence "Public Domain" :depends-on (cl-glfw-opengl) :components
 ((:file "opengl-ati_envmap_bumpmap"))) 