;;;; This file was automatically generated by /home/bill/programming/cl-glfw/generators/make-bindings-from-spec.lisp

(defpackage #:cl-glfw-opengl-apple_specular_vector-system
  (:use #:asdf #:cl)) 
(in-package #:cl-glfw-opengl-apple_specular_vector-system) 
(defsystem cl-glfw-opengl-apple_specular_vector :description
 "cl-glfw's apple_specular_vector binding" :author
 "Generated by cl-glfw's /home/bill/programming/cl-glfw/generators/make-bindings-from-spec.lisp"
 :licence "Public Domain" :depends-on (cl-glfw-opengl-core) :components
 ((:file "opengl-apple_specular_vector"))) 
