;;;; This file was automatically generated by /home/bill/programming/cl-glfw/generators/make-bindings-from-spec.lisp

(defpackage #:cl-glfw-opengl-3dfx_texture_compression_fxt1-system
  (:use #:asdf #:cl)) 
(in-package #:cl-glfw-opengl-3dfx_texture_compression_fxt1-system) 
(defsystem cl-glfw-opengl-3dfx_texture_compression_fxt1 :description
 "cl-glfw's 3dfx_texture_compression_fxt1 binding" :author
 "Generated by cl-glfw's /home/bill/programming/cl-glfw/generators/make-bindings-from-spec.lisp"
 :licence "Public Domain" :depends-on (cl-glfw-opengl-core) :components
 ((:file "opengl-3dfx_texture_compression_fxt1"))) 
