
(defpackage #:cl-glfw-opengl-arb_color_buffer_float-system (:use #:asdf #:cl)) 
(in-package #:cl-glfw-opengl-arb_color_buffer_float-system) 
(defsystem cl-glfw-opengl-arb_color_buffer_float :description
 "cl-glfw's cl-glfw-opengl-arb_color_buffer_float Binding" :author
 "Generated by cl-glfw's /home/bill/programming/cl-glfw/generators/make-bindings-from-spec.lisp"
 :licence "Public Domain" :depends-on (cl-glfw-opengl) :components
 ((:file "opengl-arb_color_buffer_float"))) 