;;;; This file was automatically generated by /home/bill/programming/cl-glfw/generators/make-bindings-from-spec.lisp

(defpackage #:cl-glfw-opengl-oml_resample-system
  (:use #:asdf #:cl)) 
(in-package #:cl-glfw-opengl-oml_resample-system) 
(defsystem cl-glfw-opengl-oml_resample :description
 "cl-glfw's oml_resample binding" :author
 "Generated by cl-glfw's /home/bill/programming/cl-glfw/generators/make-bindings-from-spec.lisp"
 :licence "Public Domain" :depends-on (cl-glfw-opengl-core) :components
 ((:file "opengl-oml_resample"))) 
