;;;; This file was automatically generated by nil

(defpackage #:cl-glfw-opengl-sun_mesh_array-system (:use #:asdf #:cl)) 
(in-package #:cl-glfw-opengl-sun_mesh_array-system) 
(defsystem cl-glfw-opengl-sun_mesh_array :description
 "cl-glfw's sun_mesh_array binding" :author "Generated by cl-glfw's nil"
 :licence "Public Domain" :depends-on (cl-glfw-opengl) :components
 ((:file "opengl-sun_mesh_array"))) 