
(defpackage #:cl-glfw-opengl-ati_fragment_shader-system (:use #:asdf #:cl)) 
(in-package #:cl-glfw-opengl-ati_fragment_shader-system) 
(defsystem cl-glfw-opengl-ati_fragment_shader :description
 "cl-glfw's cl-glfw-opengl-ati_fragment_shader Binding" :author
 "Generated by cl-glfw's /home/bill/programming/cl-glfw/generators/make-bindings-from-spec.lisp"
 :licence "Public Domain" :depends-on (cl-glfw-opengl) :components
 ((:file "opengl-ati_fragment_shader"))) 