
(defpackage #:cl-glfw-opengl-nv_half_float-system (:use #:asdf #:cl)) 
(in-package #:cl-glfw-opengl-nv_half_float-system) 
(defsystem cl-glfw-opengl-nv_half_float :description
 "cl-glfw's cl-glfw-opengl-nv_half_float Binding" :author
 "Generated by cl-glfw's /home/bill/programming/cl-glfw/generators/make-bindings-from-spec.lisp"
 :license "Public Domain" :depends-on (cl-glfw) :components
 ((:module lib :components ((:file "opengl-nv_half_float"))))) 