;;;; This file was automatically generated by /home/bill/programming/cl-glfw/generators/make-bindings-from-spec.lisp

(defpackage #:cl-glfw-opengl-sgix_instruments-system
  (:use #:asdf #:cl)) 
(in-package #:cl-glfw-opengl-sgix_instruments-system) 
(defsystem cl-glfw-opengl-sgix_instruments :description
 "cl-glfw's sgix_instruments binding" :author
 "Generated by cl-glfw's /home/bill/programming/cl-glfw/generators/make-bindings-from-spec.lisp"
 :licence "Public Domain" :depends-on (cl-glfw-opengl-core) :components
 ((:file "opengl-sgix_instruments"))) 
