
(defpackage #:cl-glfw-opengl-sgix_framezoom-system (:use #:asdf #:cl)) 
(in-package #:cl-glfw-opengl-sgix_framezoom-system) 
(defsystem cl-glfw-opengl-sgix_framezoom :description
 "cl-glfw's cl-glfw-opengl-sgix_framezoom Binding" :author
 "Generated by cl-glfw's /home/bill/programming/cl-glfw/generators/make-bindings-from-spec.lisp"
 :licence "Public Domain" :depends-on (cl-glfw-opengl) :components
 ((:file "opengl-sgix_framezoom"))) 