;;;; This file was automatically generated by nil

(defpackage #:cl-glfw-opengl-ext_pixel_transform-system (:use #:asdf #:cl)) 
(in-package #:cl-glfw-opengl-ext_pixel_transform-system) 
(defsystem cl-glfw-opengl-ext_pixel_transform :description
 "cl-glfw's ext_pixel_transform binding" :author "Generated by cl-glfw's nil"
 :licence "Public Domain" :depends-on (cl-glfw-opengl) :components
 ((:file "opengl-ext_pixel_transform"))) 