;;;; This file was automatically generated by nil

(defpackage #:cl-glfw-opengl-ext_depth_bounds_test-system (:use #:asdf #:cl)) 
(in-package #:cl-glfw-opengl-ext_depth_bounds_test-system) 
(defsystem cl-glfw-opengl-ext_depth_bounds_test :description
 "cl-glfw's ext_depth_bounds_test binding" :author "Generated by cl-glfw's nil"
 :licence "Public Domain" :depends-on (cl-glfw-opengl) :components
 ((:file "opengl-ext_depth_bounds_test"))) 