;;;; This file was automatically generated by /home/bill/programming/cl-glfw/generators/make-bindings-from-spec.lisp

(defpackage #:cl-glfw-opengl-nv_fog_distance-system
  (:use #:asdf #:cl)) 
(in-package #:cl-glfw-opengl-nv_fog_distance-system) 
(defsystem cl-glfw-opengl-nv_fog_distance :description
 "cl-glfw's nv_fog_distance binding" :author
 "Generated by cl-glfw's /home/bill/programming/cl-glfw/generators/make-bindings-from-spec.lisp"
 :licence "Public Domain" :depends-on (cl-glfw-opengl-core) :components
 ((:file "opengl-nv_fog_distance"))) 
