;;;; This file was automatically generated by /home/bill/programming/cl-glfw/generators/make-bindings-from-spec.lisp

(defpackage #:cl-glfw-opengl-arb_texture_cube_map_array-system
  (:use #:asdf #:cl)) 
(in-package #:cl-glfw-opengl-arb_texture_cube_map_array-system) 
(defsystem cl-glfw-opengl-arb_texture_cube_map_array :description
 "cl-glfw's arb_texture_cube_map_array binding" :author
 "Generated by cl-glfw's /home/bill/programming/cl-glfw/generators/make-bindings-from-spec.lisp"
 :licence "Public Domain" :depends-on (cl-glfw-opengl-core) :components
 ((:file "opengl-arb_texture_cube_map_array"))) 
