;;;; This file was automatically generated by /home/bill/programming/cl-glfw/generators/make-bindings-from-spec.lisp

(defpackage #:cl-glfw-opengl-amd_blend_minmax_factor-system
  (:use #:asdf #:cl)) 
(in-package #:cl-glfw-opengl-amd_blend_minmax_factor-system) 
(defsystem cl-glfw-opengl-amd_blend_minmax_factor :description
 "cl-glfw's amd_blend_minmax_factor binding" :author
 "Generated by cl-glfw's /home/bill/programming/cl-glfw/generators/make-bindings-from-spec.lisp"
 :licence "Public Domain" :depends-on (cl-glfw-opengl-core) :components
 ((:file "opengl-amd_blend_minmax_factor"))) 
