;;;; This file was automatically generated by /home/bill/programming/cl-glfw/generators/make-bindings-from-spec.lisp

(in-package #:cl-glfw-opengl) 

;;;; nv_texture_expand_normal

(defconstant +texture-unsigned-remap-mode-nv+ #x888F) 
(defconstant +texture-unsigned-remap-mode-nv+ #x888F) 
