;;;; This file was automatically generated by /home/bill/programming/cl-glfw/generators/make-bindings-from-spec.lisp

(in-package #:cl-glfw-opengl) 

;;;; apple_texture_range

(defconstant +texture-storage-hint-apple+ #x85BC) 
(defconstant +storage-private-apple+ #x85BD) 
(defconstant +storage-cached-apple+ #x85BE) 
(defconstant +storage-shared-apple+ #x85BF) 
(defconstant +storage-cached-apple+ #x85BE) 
(defconstant +storage-shared-apple+ #x85BF) 
(defconstant +texture-range-length-apple+ #x85B7) 
(defconstant +texture-range-pointer-apple+ #x85B8) 
(defconstant +texture-storage-hint-apple+ #x85BC) 
(defconstant +storage-private-apple+ #x85BD) 
(defconstant +storage-cached-apple+ #x85BE) 
(defconstant +storage-shared-apple+ #x85BF) 
(defglextfun "GetTexParameterPointervAPPLE" get-tex-parameter-pointerv-apple
 :return "void" :args
 ((:name |target| :type |GLenum| :direction :in)
  (:name |pname| :type |GLenum| :direction :in)
  (:name |params| :type |VoidPointer| :direction :out :array t :size #x1))
 :category "APPLE_texture_range" :deprecated nil :version "1.2") 
(defglextfun "TextureRangeAPPLE" texture-range-apple :return "void" :args
 ((:name |target| :type |GLenum| :direction :in)
  (:name |length| :type |SizeI| :direction :in)
  (:name |pointer| :type |Void| :direction :in :array t :size length))
 :category "APPLE_texture_range" :deprecated nil :version "1.2") 
(make-extension-loader |APPLE_texture_range|
 (("GetTexParameterPointervAPPLE" get-tex-parameter-pointerv-apple :return
   "void" :args
   ((:name |target| :type |GLenum| :direction :in)
    (:name |pname| :type |GLenum| :direction :in)
    (:name |params| :type |VoidPointer| :direction :out :array t :size #x1))
   :category "APPLE_texture_range" :deprecated nil :version "1.2")
  ("TextureRangeAPPLE" texture-range-apple :return "void" :args
   ((:name |target| :type |GLenum| :direction :in)
    (:name |length| :type |SizeI| :direction :in)
    (:name |pointer| :type |Void| :direction :in :array t :size length))
   :category "APPLE_texture_range" :deprecated nil :version "1.2"))) 
