;;;; This file was automatically generated by /home/bill/programming/cl-glfw/generators/make-bindings-from-spec.lisp

(in-package #:cl-glfw-opengl) 

;;;; win_specular_fog

(defconstant +fog-specular-texture-win+ #x80EC) 
