;;;; This file was automatically generated by /home/bill/programming/cl-glfw/generators/make-bindings-from-spec.lisp

(in-package #:cl-glfw-opengl) 

;;;; arb_multisample

(defconstant +multisample-bit-arb+ #x20000000) 
(defconstant +multisample-arb+ #x809D) 
(defconstant +sample-alpha-to-coverage-arb+ #x809E) 
(defconstant +sample-alpha-to-one-arb+ #x809F) 
(defconstant +sample-coverage-arb+ #x80A0) 
(defconstant +sample-buffers-arb+ #x80A8) 
(defconstant +samples-arb+ #x80A9) 
(defconstant +sample-coverage-value-arb+ #x80AA) 
(defconstant +sample-coverage-invert-arb+ #x80AB) 
(defconstant +multisample-arb+ #x809D) 
(defconstant +sample-alpha-to-coverage-arb+ #x809E) 
(defconstant +sample-alpha-to-one-arb+ #x809F) 
(defconstant +sample-coverage-arb+ #x80A0) 
(defconstant +sample-buffers-arb+ #x80A8) 
(defconstant +samples-arb+ #x80A9) 
(defconstant +sample-coverage-value-arb+ #x80AA) 
(defconstant +sample-coverage-invert-arb+ #x80AB) 
(defconstant +multisample-bit-arb+ #x20000000) 
(defglextfun "SampleCoverageARB" sample-coverage-arb :return "void" :args
 ((:name |value| :type |ClampedFloat32| :direction :in)
  (:name |invert| :type |Boolean| :direction :in))
 :category "ARB_multisample" :deprecated nil :version "1.2") 
(make-extension-loader |ARB_multisample|
 (("SampleCoverageARB" sample-coverage-arb :return "void" :args
   ((:name |value| :type |ClampedFloat32| :direction :in)
    (:name |invert| :type |Boolean| :direction :in))
   :category "ARB_multisample" :deprecated nil :version "1.2"))) 
