;;;; This file was automatically generated by nil

(in-package #:cl-glfw-opengl) 

;;;; sgix_sprite

(defconstant +sprite-axial-sgix+ #x814C) 
(defconstant +sprite-object-aligned-sgix+ #x814D) 
(defconstant +sprite-eye-aligned-sgix+ #x814E) 