;;;; This file was automatically generated by /home/bill/programming/cl-glfw/generators/make-bindings-from-spec.lisp

(in-package #:cl-glfw-opengl) 

;;;; amd_blend_minmax_factor

(defconstant +factor-min-amd+ #x901C) 
(defconstant +factor-max-amd+ #x901D) 
(defconstant +factor-min-amd+ #x901C) 
(defconstant +factor-max-amd+ #x901D) 
