;;;; This file was automatically generated by /home/bill/programming/cl-glfw/generators/make-bindings-from-spec.lisp

(in-package #:cl-glfw-opengl) 

;;;; amd_depth_clamp_separate

(defconstant +depth-clamp-near-amd+ #x901E) 
(defconstant +depth-clamp-far-amd+ #x901F) 
(defconstant +depth-clamp-near-amd+ #x901E) 
(defconstant +depth-clamp-far-amd+ #x901F) 
