;;;; This file was automatically generated by /home/bill/programming/cl-glfw/generators/make-bindings-from-spec.lisp

(in-package #:cl-glfw-opengl) 

;;;; 3dfx_tbuffer

(defglextfun "TbufferMask3DFX" tbuffer-mask-3dfx :return "void" :args
 ((:name |mask| :type |UInt32| :direction :in)) :category "3DFX_tbuffer"
 :deprecated nil :version "1.2") 
(make-extension-loader |3DFX_tbuffer|
 (("TbufferMask3DFX" tbuffer-mask-3dfx :return "void" :args
   ((:name |mask| :type |UInt32| :direction :in)) :category "3DFX_tbuffer"
   :deprecated nil :version "1.2"))) 
