;;;; This file was automatically generated by /home/bill/programming/cl-glfw/generators/make-bindings-from-spec.lisp

(in-package #:cl-glfw-opengl) 

;;;; arb_half_float_pixel

(defconstant +half-float-arb+ #x140B) 
(defconstant +half-float-arb+ #x140B) 
