;;;; This file was automatically generated by /home/bill/programming/cl-glfw/generators/make-bindings-from-spec.lisp

(in-package #:cl-glfw-opengl) 

;;;; nv_vertex_array_range2

(defconstant +vertex-array-range-without-flush-nv+ #x8533) 
