;;;; This file was automatically generated by /home/bill/programming/cl-glfw/generators/make-bindings-from-spec.lisp

(in-package #:cl-glfw-opengl) 

;;;; arb_texture_cube_map_array

(defconstant +texture-cube-map-array+ #x9009) 
(defconstant +texture-binding-cube-map-array+ #x900A) 
(defconstant +proxy-texture-cube-map-array+ #x900B) 
(defconstant +sampler-cube-map-array+ #x900C) 
(defconstant +sampler-cube-map-array-shadow+ #x900D) 
(defconstant +int-sampler-cube-map-array+ #x900E) 
(defconstant +unsigned-int-sampler-cube-map-array+ #x900F) 
(defconstant +texture-cube-map-array-arb+ #x9009) 
(defconstant +texture-binding-cube-map-array-arb+ #x900A) 
(defconstant +proxy-texture-cube-map-array-arb+ #x900B) 
(defconstant +sampler-cube-map-array-arb+ #x900C) 
(defconstant +sampler-cube-map-array-shadow-arb+ #x900D) 
(defconstant +int-sampler-cube-map-array-arb+ #x900E) 
(defconstant +unsigned-int-sampler-cube-map-array-arb+ #x900F) 
