;;;; This file was automatically generated by /home/bill/programming/cl-glfw/generators/make-bindings-from-spec.lisp

(in-package #:cl-glfw-opengl) 

;;;; mesa_resize_buffers

(defglextfun "ResizeBuffersMESA" resize-buffers-mesa :return "void" :args nil
 :category "MESA_resize_buffers" :deprecated nil :version "1.0") 
(make-extension-loader |MESA_resize_buffers|
 (("ResizeBuffersMESA" resize-buffers-mesa :return "void" :args nil :category
   "MESA_resize_buffers" :deprecated nil :version "1.0"))) 
