;;;; This file was automatically generated by nil

(in-package #:cl-glfw-opengl) 

;;;; ext_pixel_transform

(defconstant +pixel-transform-2d-ext+ #x8330) 
(defconstant +pixel-mag-filter-ext+ #x8331) 
(defconstant +pixel-min-filter-ext+ #x8332) 
(defconstant +pixel-cubic-weight-ext+ #x8333) 
(defconstant +cubic-ext+ #x8334) 
(defconstant +average-ext+ #x8335) 
(defconstant +pixel-transform-2d-stack-depth-ext+ #x8336) 
(defconstant +max-pixel-transform-2d-stack-depth-ext+ #x8337) 
(defconstant +pixel-transform-2d-matrix-ext+ #x8338) 