;;;; This file was automatically generated by /home/bill/programming/cl-glfw/generators/make-bindings-from-spec.lisp

(in-package #:cl-glfw-opengl) 

;;;; sgix_tag_sample_buffer

(defglextfun "TagSampleBufferSGIX" tag-sample-buffer-sgix :return "void" :args
 nil :category "SGIX_tag_sample_buffer" :version "1.0") 
