;;;; This file was automatically generated by /home/bill/programming/cl-glfw/generators/make-bindings-from-spec.lisp

(in-package #:cl-glfw-opengl) 

;;;; arb_texture_border_clamp

(defconstant +clamp-to-border-arb+ #x812D) 
(defconstant +clamp-to-border-arb+ #x812D) 
