;;;; This file was automatically generated by /home/bill/programming/cl-glfw/generators/make-bindings-from-spec.lisp

(in-package #:cl-glfw-opengl) 

;;;; arb_depth_clamp

(defconstant +depth-clamp+ #x864F) 
(defconstant +depth-clamp+ #x864F) 
