;;;; This file was automatically generated by /home/bill/programming/cl-glfw/generators/make-bindings-from-spec.lisp

(in-package #:cl-glfw-opengl) 

;;;; ext_light_texture

(defconstant +fragment-material-ext+ #x8349) 
(defconstant +fragment-normal-ext+ #x834A) 
(defconstant +fragment-color-ext+ #x834C) 
(defconstant +attenuation-ext+ #x834D) 
(defconstant +shadow-attenuation-ext+ #x834E) 
(defconstant +texture-application-mode-ext+ #x834F) 
(defconstant +texture-light-ext+ #x8350) 
(defconstant +texture-material-face-ext+ #x8351) 
(defconstant +texture-material-parameter-ext+ #x8352) 
(defconstant +fragment-depth-ext+ #x8452) 
(defglextfun "TextureMaterialEXT" texture-material-ext :return "void" :args
 ((:name |face| :type |MaterialFace| :direction :in)
  (:name |mode| :type |MaterialParameter| :direction :in))
 :category "EXT_light_texture" :deprecated nil :version "1.1") 
(defglextfun "TextureLightEXT" texture-light-ext :return "void" :args
 ((:name |pname| :type |LightTexturePNameEXT| :direction :in)) :category
 "EXT_light_texture" :deprecated nil :version "1.1") 
(defglextfun "ApplyTextureEXT" apply-texture-ext :return "void" :args
 ((:name |mode| :type |LightTextureModeEXT| :direction :in)) :category
 "EXT_light_texture" :deprecated nil :version "1.1") 
(make-extension-loader |EXT_light_texture|
 (("TextureMaterialEXT" texture-material-ext :return "void" :args
   ((:name |face| :type |MaterialFace| :direction :in)
    (:name |mode| :type |MaterialParameter| :direction :in))
   :category "EXT_light_texture" :deprecated nil :version "1.1")
  ("TextureLightEXT" texture-light-ext :return "void" :args
   ((:name |pname| :type |LightTexturePNameEXT| :direction :in)) :category
   "EXT_light_texture" :deprecated nil :version "1.1")
  ("ApplyTextureEXT" apply-texture-ext :return "void" :args
   ((:name |mode| :type |LightTextureModeEXT| :direction :in)) :category
   "EXT_light_texture" :deprecated nil :version "1.1"))) 
