;;;; This file was automatically generated by /home/bill/programming/cl-glfw/generators/make-bindings-from-spec.lisp

(in-package #:cl-glfw-opengl) 

;;;; arb_seamless_cube_map

(defconstant +texture-cube-map-seamless+ #x884F) 
(defconstant +texture-cube-map-seamless+ #x884F) 
