;;;; This file was automatically generated by /home/bill/programming/cl-glfw/generators/make-bindings-from-spec.lisp

(in-package #:cl-glfw-opengl) 

;;;; ati_text_fragment_shader

(defconstant +text-fragment-shader-ati+ #x8200) 
(defconstant +text-fragment-shader-ati+ #x8200) 
