;;;; This file was automatically generated by /home/bill/programming/cl-glfw/generators/make-bindings-from-spec.lisp

(in-package #:cl-glfw-opengl) 

;;;; apple_client_storage

(defconstant +unpack-client-storage-apple+ #x85B2) 
(defconstant +buffer-object-apple+ #x85B3) 
(defconstant +storage-client-apple+ #x85B4) 
(defconstant +unpack-client-storage-apple+ #x85B2) 
