;;;; This file was automatically generated by /home/bill/programming/cl-glfw/generators/make-bindings-from-spec.lisp

(in-package #:cl-glfw-opengl) 

;;;; arb_texture_rgb10_a2ui

(defconstant +rgb10-a2ui+ #x906F) 
(defconstant +rgb10-a2ui+ #x906F) 
