;;;; This file was automatically generated by /home/bill/programming/cl-glfw/generators/make-bindings-from-spec.lisp

(in-package #:cl-glfw-opengl) 

;;;; version_1_2

(defconstant +max-elements-vertices+ #x80E8) 
(defconstant +max-elements-indices+ #x80E9) 
(defconstant +pack-skip-images+ #x806B) 
(defconstant +pack-image-height+ #x806C) 
(defconstant +unpack-skip-images+ #x806D) 
(defconstant +unpack-image-height+ #x806E) 
(defconstant +texture-3d+ #x806F) 
(defconstant +proxy-texture-3d+ #x8070) 
(defconstant +texture-depth+ #x8071) 
(defconstant +texture-wrap-r+ #x8072) 
(defconstant +max-3d-texture-size+ #x8073) 
(defconstant +max-elements-vertices+ #x80E8) 
(defconstant +max-elements-indices+ #x80E9) 
(defglfun "CopyTexSubImage3D" copy-tex-sub-image-3d :return "void" :args
 ((:name |target| :type |TextureTarget| :direction :in)
  (:name |level| :type |CheckedInt32| :direction :in)
  (:name |xoffset| :type |CheckedInt32| :direction :in)
  (:name |yoffset| :type |CheckedInt32| :direction :in)
  (:name |zoffset| :type |CheckedInt32| :direction :in)
  (:name |x| :type |WinCoord| :direction :in)
  (:name |y| :type |WinCoord| :direction :in)
  (:name |width| :type |SizeI| :direction :in)
  (:name |height| :type |SizeI| :direction :in))
 :category "VERSION_1_2" :version "1.2") 
(defglfun "TexSubImage3D" tex-sub-image-3d :return "void" :args
 ((:name |target| :type |TextureTarget| :direction :in)
  (:name |level| :type |CheckedInt32| :direction :in)
  (:name |xoffset| :type |CheckedInt32| :direction :in)
  (:name |yoffset| :type |CheckedInt32| :direction :in)
  (:name |zoffset| :type |CheckedInt32| :direction :in)
  (:name |width| :type |SizeI| :direction :in)
  (:name |height| :type |SizeI| :direction :in)
  (:name |depth| :type |SizeI| :direction :in)
  (:name |format| :type |PixelFormat| :direction :in)
  (:name |type| :type |PixelType| :direction :in)
  (:name |pixels| :type |Void| :direction :in :array t :size
   (|format| |type| |width| |height| |depth|)))
 :category "VERSION_1_2" :version "1.2") 
(defglfun "TexImage3D" tex-image-3d :return "void" :args
 ((:name |target| :type |TextureTarget| :direction :in)
  (:name |level| :type |CheckedInt32| :direction :in)
  (:name |internalformat| :type |TextureComponentCount| :direction :in)
  (:name |width| :type |SizeI| :direction :in)
  (:name |height| :type |SizeI| :direction :in)
  (:name |depth| :type |SizeI| :direction :in)
  (:name |border| :type |CheckedInt32| :direction :in)
  (:name |format| :type |PixelFormat| :direction :in)
  (:name |type| :type |PixelType| :direction :in)
  (:name |pixels| :type |Void| :direction :in :array t :size
   (|format| |type| |width| |height| |depth|)))
 :category "VERSION_1_2" :version "1.2") 
(defglfun "ResetMinmax" reset-minmax :return "void" :args
 ((:name |target| :type |MinmaxTarget| :direction :in)) :category "VERSION_1_2"
 :version "1.2") 
(defglfun "ResetHistogram" reset-histogram :return "void" :args
 ((:name |target| :type |HistogramTarget| :direction :in)) :category
 "VERSION_1_2" :version "1.2") 
(defglfun "Minmax" minmax :return "void" :args
 ((:name |target| :type |MinmaxTarget| :direction :in)
  (:name |internalformat| :type |PixelInternalFormat| :direction :in)
  (:name |sink| :type |Boolean| :direction :in))
 :category "VERSION_1_2" :version "1.2") 
(defglfun "Histogram" histogram :return "void" :args
 ((:name |target| :type |HistogramTarget| :direction :in)
  (:name |width| :type |SizeI| :direction :in)
  (:name |internalformat| :type |PixelInternalFormat| :direction :in)
  (:name |sink| :type |Boolean| :direction :in))
 :category "VERSION_1_2" :version "1.2") 
(defglfun "GetMinmaxParameteriv" get-minmax-parameter-iv :return "void" :args
 ((:name |target| :type |MinmaxTarget| :direction :in)
  (:name |pname| :type |GetMinmaxParameterPName| :direction :in)
  (:name |params| :type |Int32| :direction :out :array t :size (|pname|)))
 :category "VERSION_1_2" :version "1.2") 
(defglfun "GetMinmaxParameterfv" get-minmax-parameter-fv :return "void" :args
 ((:name |target| :type |MinmaxTarget| :direction :in)
  (:name |pname| :type |GetMinmaxParameterPName| :direction :in)
  (:name |params| :type |Float32| :direction :out :array t :size (|pname|)))
 :category "VERSION_1_2" :version "1.2") 
(defglfun "GetMinmax" get-minmax :return "void" :args
 ((:name |target| :type |MinmaxTarget| :direction :in)
  (:name |reset| :type |Boolean| :direction :in)
  (:name |format| :type |PixelFormat| :direction :in)
  (:name |type| :type |PixelType| :direction :in)
  (:name |values| :type |Void| :direction :out :array t :size
   (|target| |format| |type|)))
 :category "VERSION_1_2" :version "1.2") 
(defglfun "GetHistogramParameteriv" get-histogram-parameter-iv :return "void"
 :args
 ((:name |target| :type |HistogramTarget| :direction :in)
  (:name |pname| :type |GetHistogramParameterPName| :direction :in)
  (:name |params| :type |Int32| :direction :out :array t :size (|pname|)))
 :category "VERSION_1_2" :version "1.2") 
(defglfun "GetHistogramParameterfv" get-histogram-parameter-fv :return "void"
 :args
 ((:name |target| :type |HistogramTarget| :direction :in)
  (:name |pname| :type |GetHistogramParameterPName| :direction :in)
  (:name |params| :type |Float32| :direction :out :array t :size (|pname|)))
 :category "VERSION_1_2" :version "1.2") 
(defglfun "GetHistogram" get-histogram :return "void" :args
 ((:name |target| :type |HistogramTarget| :direction :in)
  (:name |reset| :type |Boolean| :direction :in)
  (:name |format| :type |PixelFormat| :direction :in)
  (:name |type| :type |PixelType| :direction :in)
  (:name |values| :type |Void| :direction :out :array t :size
   (|target| |format| |type|)))
 :category "VERSION_1_2" :version "1.2") 
(defglfun "SeparableFilter2D" separable-filter-2d :return "void" :args
 ((:name |target| :type |SeparableTarget| :direction :in)
  (:name |internalformat| :type |PixelInternalFormat| :direction :in)
  (:name |width| :type |SizeI| :direction :in)
  (:name |height| :type |SizeI| :direction :in)
  (:name |format| :type |PixelFormat| :direction :in)
  (:name |type| :type |PixelType| :direction :in)
  (:name |row| :type |Void| :direction :in :array t :size
   (|target| |format| |type| |width|))
  (:name |column| :type |Void| :direction :in :array t :size
   (|target| |format| |type| |height|)))
 :category "VERSION_1_2" :version "1.2") 
(defglfun "GetSeparableFilter" get-separable-filter :return "void" :args
 ((:name |target| :type |SeparableTarget| :direction :in)
  (:name |format| :type |PixelFormat| :direction :in)
  (:name |type| :type |PixelType| :direction :in)
  (:name |row| :type |Void| :direction :out :array t :size
   (|target| |format| |type|))
  (:name |column| :type |Void| :direction :out :array t :size
   (|target| |format| |type|))
  (:name |span| :type |Void| :direction :out :array t :size
   (|target| |format| |type|)))
 :category "VERSION_1_2" :version "1.2") 
(defglfun "GetConvolutionParameteriv" get-convolution-parameter-iv :return
 "void" :args
 ((:name |target| :type |ConvolutionTarget| :direction :in)
  (:name |pname| :type |GetConvolutionParameterPName| :direction :in)
  (:name |params| :type |Int32| :direction :out :array t :size (|pname|)))
 :category "VERSION_1_2" :version "1.2") 
(defglfun "GetConvolutionParameterfv" get-convolution-parameter-fv :return
 "void" :args
 ((:name |target| :type |ConvolutionTarget| :direction :in)
  (:name |pname| :type |GetConvolutionParameterPName| :direction :in)
  (:name |params| :type |Float32| :direction :out :array t :size (|pname|)))
 :category "VERSION_1_2" :version "1.2") 
(defglfun "GetConvolutionFilter" get-convolution-filter :return "void" :args
 ((:name |target| :type |ConvolutionTarget| :direction :in)
  (:name |format| :type |PixelFormat| :direction :in)
  (:name |type| :type |PixelType| :direction :in)
  (:name |image| :type |Void| :direction :out :array t :size
   (|target| |format| |type|)))
 :category "VERSION_1_2" :version "1.2") 
(defglfun "CopyConvolutionFilter2D" copy-convolution-filter-2d :return "void"
 :args
 ((:name |target| :type |ConvolutionTarget| :direction :in)
  (:name |internalformat| :type |PixelInternalFormat| :direction :in)
  (:name |x| :type |WinCoord| :direction :in)
  (:name |y| :type |WinCoord| :direction :in)
  (:name |width| :type |SizeI| :direction :in)
  (:name |height| :type |SizeI| :direction :in))
 :category "VERSION_1_2" :version "1.2") 
(defglfun "CopyConvolutionFilter1D" copy-convolution-filter-1d :return "void"
 :args
 ((:name |target| :type |ConvolutionTarget| :direction :in)
  (:name |internalformat| :type |PixelInternalFormat| :direction :in)
  (:name |x| :type |WinCoord| :direction :in)
  (:name |y| :type |WinCoord| :direction :in)
  (:name |width| :type |SizeI| :direction :in))
 :category "VERSION_1_2" :version "1.2") 
(defglfun "ConvolutionParameteriv" convolution-parameter-iv :return "void"
 :args
 ((:name |target| :type |ConvolutionTarget| :direction :in)
  (:name |pname| :type |ConvolutionParameter| :direction :in)
  (:name |params| :type |CheckedInt32| :direction :in :array t :size
   (|pname|)))
 :category "VERSION_1_2" :version "1.2") 
(defglfun "ConvolutionParameteri" convolution-parameter-i :return "void" :args
 ((:name |target| :type |ConvolutionTarget| :direction :in)
  (:name |pname| :type |ConvolutionParameter| :direction :in)
  (:name |params| :type |CheckedInt32| :direction :in))
 :category "VERSION_1_2" :version "1.2") 
(defglfun "ConvolutionParameterfv" convolution-parameter-fv :return "void"
 :args
 ((:name |target| :type |ConvolutionTarget| :direction :in)
  (:name |pname| :type |ConvolutionParameter| :direction :in)
  (:name |params| :type |CheckedFloat32| :direction :in :array t :size
   (|pname|)))
 :category "VERSION_1_2" :version "1.2") 
(defglfun "ConvolutionParameterf" convolution-parameter-f :return "void" :args
 ((:name |target| :type |ConvolutionTarget| :direction :in)
  (:name |pname| :type |ConvolutionParameter| :direction :in)
  (:name |params| :type |CheckedFloat32| :direction :in))
 :category "VERSION_1_2" :version "1.2") 
(defglfun "ConvolutionFilter2D" convolution-filter-2d :return "void" :args
 ((:name |target| :type |ConvolutionTarget| :direction :in)
  (:name |internalformat| :type |PixelInternalFormat| :direction :in)
  (:name |width| :type |SizeI| :direction :in)
  (:name |height| :type |SizeI| :direction :in)
  (:name |format| :type |PixelFormat| :direction :in)
  (:name |type| :type |PixelType| :direction :in)
  (:name |image| :type |Void| :direction :in :array t :size
   (|format| |type| |width| |height|)))
 :category "VERSION_1_2" :version "1.2") 
(defglfun "ConvolutionFilter1D" convolution-filter-1d :return "void" :args
 ((:name |target| :type |ConvolutionTarget| :direction :in)
  (:name |internalformat| :type |PixelInternalFormat| :direction :in)
  (:name |width| :type |SizeI| :direction :in)
  (:name |format| :type |PixelFormat| :direction :in)
  (:name |type| :type |PixelType| :direction :in)
  (:name |image| :type |Void| :direction :in :array t :size
   (|format| |type| |width|)))
 :category "VERSION_1_2" :version "1.2") 
(defglfun "CopyColorSubTable" copy-color-sub-table :return "void" :args
 ((:name |target| :type |ColorTableTarget| :direction :in)
  (:name |start| :type |SizeI| :direction :in)
  (:name |x| :type |WinCoord| :direction :in)
  (:name |y| :type |WinCoord| :direction :in)
  (:name |width| :type |SizeI| :direction :in))
 :category "VERSION_1_2" :version "1.2") 
(defglfun "ColorSubTable" color-sub-table :return "void" :args
 ((:name |target| :type |ColorTableTarget| :direction :in)
  (:name |start| :type |SizeI| :direction :in)
  (:name |count| :type |SizeI| :direction :in)
  (:name |format| :type |PixelFormat| :direction :in)
  (:name |type| :type |PixelType| :direction :in)
  (:name |data| :type |Void| :direction :in :array t :size
   (|format| |type| |count|)))
 :category "VERSION_1_2" :version "1.2") 
(defglfun "GetColorTableParameteriv" get-color-table-parameter-iv :return
 "void" :args
 ((:name |target| :type |ColorTableTarget| :direction :in)
  (:name |pname| :type |GetColorTableParameterPName| :direction :in)
  (:name |params| :type |Int32| :direction :out :array t :size (|pname|)))
 :category "VERSION_1_2" :version "1.2") 
(defglfun "GetColorTableParameterfv" get-color-table-parameter-fv :return
 "void" :args
 ((:name |target| :type |ColorTableTarget| :direction :in)
  (:name |pname| :type |GetColorTableParameterPName| :direction :in)
  (:name |params| :type |Float32| :direction :out :array t :size (|pname|)))
 :category "VERSION_1_2" :version "1.2") 
(defglfun "GetColorTable" get-color-table :return "void" :args
 ((:name |target| :type |ColorTableTarget| :direction :in)
  (:name |format| :type |PixelFormat| :direction :in)
  (:name |type| :type |PixelType| :direction :in)
  (:name |table| :type |Void| :direction :out :array t :size
   (|target| |format| |type|)))
 :category "VERSION_1_2" :version "1.2") 
(defglfun "CopyColorTable" copy-color-table :return "void" :args
 ((:name |target| :type |ColorTableTarget| :direction :in)
  (:name |internalformat| :type |PixelInternalFormat| :direction :in)
  (:name |x| :type |WinCoord| :direction :in)
  (:name |y| :type |WinCoord| :direction :in)
  (:name |width| :type |SizeI| :direction :in))
 :category "VERSION_1_2" :version "1.2") 
(defglfun "ColorTableParameteriv" color-table-parameter-iv :return "void" :args
 ((:name |target| :type |ColorTableTarget| :direction :in)
  (:name |pname| :type |ColorTableParameterPName| :direction :in)
  (:name |params| :type |CheckedInt32| :direction :in :array t :size
   (|pname|)))
 :category "VERSION_1_2" :version "1.2") 
(defglfun "ColorTableParameterfv" color-table-parameter-fv :return "void" :args
 ((:name |target| :type |ColorTableTarget| :direction :in)
  (:name |pname| :type |ColorTableParameterPName| :direction :in)
  (:name |params| :type |CheckedFloat32| :direction :in :array t :size
   (|pname|)))
 :category "VERSION_1_2" :version "1.2") 
(defglfun "ColorTable" color-table :return "void" :args
 ((:name |target| :type |ColorTableTarget| :direction :in)
  (:name |internalformat| :type |PixelInternalFormat| :direction :in)
  (:name |width| :type |SizeI| :direction :in)
  (:name |format| :type |PixelFormat| :direction :in)
  (:name |type| :type |PixelType| :direction :in)
  (:name |table| :type |Void| :direction :in :array t :size
   (|format| |type| |width|)))
 :category "VERSION_1_2" :version "1.2") 
(defglfun "DrawRangeElements" draw-range-elements :return "void" :args
 ((:name |mode| :type |BeginMode| :direction :in)
  (:name |start| :type |UInt32| :direction :in)
  (:name |end| :type |UInt32| :direction :in)
  (:name |count| :type |SizeI| :direction :in)
  (:name |type| :type |DrawElementsType| :direction :in)
  (:name |indices| :type |Void| :direction :in :array t :size
   (|count| |type|)))
 :category "VERSION_1_2" :version "1.2") 
(defglfun "BlendEquation" blend-equation :return "void" :args
 ((:name |mode| :type |BlendEquationMode| :direction :in)) :category
 "VERSION_1_2" :version "1.2") 
(defglfun "BlendColor" blend-color :return "void" :args
 ((:name |red| :type |ClampedColorF| :direction :in)
  (:name |green| :type |ClampedColorF| :direction :in)
  (:name |blue| :type |ClampedColorF| :direction :in)
  (:name |alpha| :type |ClampedColorF| :direction :in))
 :category "VERSION_1_2" :version "1.2") 
