;;;; This file was automatically generated by /home/bill/programming/cl-glfw/generators/make-bindings-from-spec.lisp

(in-package #:cl-glfw-opengl) 

;;;; ext_gpu_program_parameters

(defglextfun "ProgramLocalParameters4fvEXT" program-local-parameters-4fv-ext
 :return "void" :args
 ((:name |target| :type |ProgramTargetARB| :direction :in)
  (:name |index| :type |UInt32| :direction :in)
  (:name |count| :type |SizeI| :direction :in)
  (:name |params| :type |Float32| :direction :in :array t :size count*4))
 :category "EXT_gpu_program_parameters" :deprecated nil :version "1.2") 
(defglextfun "ProgramEnvParameters4fvEXT" program-env-parameters-4fv-ext
 :return "void" :args
 ((:name |target| :type |ProgramTargetARB| :direction :in)
  (:name |index| :type |UInt32| :direction :in)
  (:name |count| :type |SizeI| :direction :in)
  (:name |params| :type |Float32| :direction :in :array t :size count*4))
 :category "EXT_gpu_program_parameters" :deprecated nil :version "1.2") 
(make-extension-loader |EXT_gpu_program_parameters|
 (("ProgramLocalParameters4fvEXT" program-local-parameters-4fv-ext :return
   "void" :args
   ((:name |target| :type |ProgramTargetARB| :direction :in)
    (:name |index| :type |UInt32| :direction :in)
    (:name |count| :type |SizeI| :direction :in)
    (:name |params| :type |Float32| :direction :in :array t :size count*4))
   :category "EXT_gpu_program_parameters" :deprecated nil :version "1.2")
  ("ProgramEnvParameters4fvEXT" program-env-parameters-4fv-ext :return "void"
   :args
   ((:name |target| :type |ProgramTargetARB| :direction :in)
    (:name |index| :type |UInt32| :direction :in)
    (:name |count| :type |SizeI| :direction :in)
    (:name |params| :type |Float32| :direction :in :array t :size count*4))
   :category "EXT_gpu_program_parameters" :deprecated nil :version "1.2"))) 
