;;;; This file was automatically generated by /home/bill/programming/cl-glfw/generators/make-bindings-from-spec.lisp

(in-package #:cl-glfw-opengl) 

;;;; arb_texture_compression_rgtc

(defconstant +compressed-red-rgtc1+ #x8DBB) 
(defconstant +compressed-signed-red-rgtc1+ #x8DBC) 
(defconstant +compressed-rg-rgtc2+ #x8DBD) 
(defconstant +compressed-signed-rg-rgtc2+ #x8DBE) 
