;;;; This file was automatically generated by /home/bill/programming/cl-glfw/generators/make-bindings-from-spec.lisp

(in-package #:cl-glfw-opengl) 

;;;; arb_uniform_buffer_object

(defconstant +uniform-buffer-binding+ #x8A28) 
(defconstant +uniform-buffer-start+ #x8A29) 
(defconstant +uniform-buffer-size+ #x8A2A) 
(defconstant +max-vertex-uniform-blocks+ #x8A2B) 
(defconstant +max-geometry-uniform-blocks+ #x8A2C) 
(defconstant +max-fragment-uniform-blocks+ #x8A2D) 
(defconstant +max-combined-uniform-blocks+ #x8A2E) 
(defconstant +max-uniform-buffer-bindings+ #x8A2F) 
(defconstant +max-uniform-block-size+ #x8A30) 
(defconstant +max-combined-vertex-uniform-components+ #x8A31) 
(defconstant +max-combined-geometry-uniform-components+ #x8A32) 
(defconstant +max-combined-fragment-uniform-components+ #x8A33) 
(defconstant +uniform-buffer-offset-alignment+ #x8A34) 
(defconstant +active-uniform-block-max-name-length+ #x8A35) 
(defconstant +active-uniform-blocks+ #x8A36) 
(defconstant +uniform-type+ #x8A37) 
(defconstant +uniform-size+ #x8A38) 
(defconstant +uniform-name-length+ #x8A39) 
(defconstant +uniform-block-index+ #x8A3A) 
(defconstant +uniform-offset+ #x8A3B) 
(defconstant +uniform-array-stride+ #x8A3C) 
(defconstant +uniform-matrix-stride+ #x8A3D) 
(defconstant +uniform-is-row-major+ #x8A3E) 
(defconstant +uniform-block-binding+ #x8A3F) 
(defconstant +uniform-block-data-size+ #x8A40) 
(defconstant +uniform-block-name-length+ #x8A41) 
(defconstant +uniform-block-active-uniforms+ #x8A42) 
(defconstant +uniform-block-active-uniform-indices+ #x8A43) 
(defconstant +uniform-block-referenced-by-vertex-shader+ #x8A44) 
(defconstant +uniform-block-referenced-by-geometry-shader+ #x8A45) 
(defconstant +uniform-block-referenced-by-fragment-shader+ #x8A46) 
(defconstant +invalid-index+ #xFFFFFFFF) 
(defconstant +uniform-buffer+ #x8A11) 
(defconstant +uniform-buffer-binding+ #x8A28) 
(defconstant +uniform-buffer-start+ #x8A29) 
(defconstant +uniform-buffer-size+ #x8A2A) 
(defconstant +max-vertex-uniform-blocks+ #x8A2B) 
(defconstant +max-geometry-uniform-blocks+ #x8A2C) 
(defconstant +max-fragment-uniform-blocks+ #x8A2D) 
(defconstant +max-combined-uniform-blocks+ #x8A2E) 
(defconstant +max-uniform-buffer-bindings+ #x8A2F) 
(defconstant +max-uniform-block-size+ #x8A30) 
(defconstant +max-combined-vertex-uniform-components+ #x8A31) 
(defconstant +max-combined-geometry-uniform-components+ #x8A32) 
(defconstant +max-combined-fragment-uniform-components+ #x8A33) 
(defconstant +uniform-buffer-offset-alignment+ #x8A34) 
(defconstant +active-uniform-block-max-name-length+ #x8A35) 
(defconstant +active-uniform-blocks+ #x8A36) 
(defconstant +uniform-type+ #x8A37) 
(defconstant +uniform-size+ #x8A38) 
(defconstant +uniform-name-length+ #x8A39) 
(defconstant +uniform-block-index+ #x8A3A) 
(defconstant +uniform-offset+ #x8A3B) 
(defconstant +uniform-array-stride+ #x8A3C) 
(defconstant +uniform-matrix-stride+ #x8A3D) 
(defconstant +uniform-is-row-major+ #x8A3E) 
(defconstant +uniform-block-binding+ #x8A3F) 
(defconstant +uniform-block-data-size+ #x8A40) 
(defconstant +uniform-block-name-length+ #x8A41) 
(defconstant +uniform-block-active-uniforms+ #x8A42) 
(defconstant +uniform-block-active-uniform-indices+ #x8A43) 
(defconstant +uniform-block-referenced-by-vertex-shader+ #x8A44) 
(defconstant +uniform-block-referenced-by-geometry-shader+ #x8A45) 
(defconstant +uniform-block-referenced-by-fragment-shader+ #x8A46) 
(defconstant +invalid-index+ #xFFFFFFFF) 
(defglextfun "UniformBlockBinding" uniform-block-binding :return "void" :args
 ((:name |program| :type |UInt32| :direction :in)
  (:name |uniformBlockIndex| :type |UInt32| :direction :in)
  (:name |uniformBlockBinding| :type |UInt32| :direction :in))
 :category "ARB_uniform_buffer_object" :deprecated nil :version "2.0") 
(defglextfun "GetActiveUniformBlockName" get-active-uniform-block-name :return
 "void" :args
 ((:name |program| :type |UInt32| :direction :in)
  (:name |uniformBlockIndex| :type |UInt32| :direction :in)
  (:name |bufSize| :type |SizeI| :direction :in)
  (:name |length| :type |SizeI| :direction :out :array t :size #x1)
  (:name |uniformBlockName| :type |Char| :direction :out :array t :size
   bufsize))
 :category "ARB_uniform_buffer_object" :deprecated nil :version "2.0") 
(defglextfun "GetActiveUniformBlockiv" get-active-uniform-block-iv :return
 "void" :args
 ((:name |program| :type |UInt32| :direction :in)
  (:name |uniformBlockIndex| :type |UInt32| :direction :in)
  (:name |pname| :type |GLenum| :direction :in)
  (:name |params| :type |Int32| :direction :out :array t :size (|pname|)))
 :category "ARB_uniform_buffer_object" :deprecated nil :version "2.0") 
(defglextfun "GetUniformBlockIndex" get-uniform-block-index :return "UInt32"
 :args
 ((:name |program| :type |UInt32| :direction :in)
  (:name |uniformBlockName| :type |Char| :direction :in :array t))
 :category "ARB_uniform_buffer_object" :deprecated nil :version "2.0") 
(defglextfun "GetActiveUniformName" get-active-uniform-name :return "void"
 :args
 ((:name |program| :type |UInt32| :direction :in)
  (:name |uniformIndex| :type |UInt32| :direction :in)
  (:name |bufSize| :type |SizeI| :direction :in)
  (:name |length| :type |SizeI| :direction :out :array t :size #x1)
  (:name |uniformName| :type |Char| :direction :out :array t :size bufsize))
 :category "ARB_uniform_buffer_object" :deprecated nil :version "2.0") 
(defglextfun "GetActiveUniformsiv" get-active-uniforms-iv :return "void" :args
 ((:name |program| :type |UInt32| :direction :in)
  (:name |uniformCount| :type |SizeI| :direction :in)
  (:name |uniformIndices| :type |UInt32| :direction :in :array t :size
   (|uniformCount|))
  (:name |pname| :type |GLenum| :direction :in)
  (:name |params| :type |Int32| :direction :out :array t :size (|pname|)))
 :category "ARB_uniform_buffer_object" :deprecated nil :version "2.0") 
(defglextfun "GetUniformIndices" get-uniform-indices :return "void" :args
 ((:name |program| :type |UInt32| :direction :in)
  (:name |uniformCount| :type |SizeI| :direction :in)
  (:name |uniformNames| :type |CharPointer| :direction :in :array t :size
   (|uniformCount|))
  (:name |uniformIndices| :type |UInt32| :direction :out :array t :size
   (|uniformCount|)))
 :category "ARB_uniform_buffer_object" :deprecated nil :version "2.0") 
(make-extension-loader |ARB_uniform_buffer_object|
 (("UniformBlockBinding" uniform-block-binding :return "void" :args
   ((:name |program| :type |UInt32| :direction :in)
    (:name |uniformBlockIndex| :type |UInt32| :direction :in)
    (:name |uniformBlockBinding| :type |UInt32| :direction :in))
   :category "ARB_uniform_buffer_object" :deprecated nil :version "2.0")
  ("GetActiveUniformBlockName" get-active-uniform-block-name :return "void"
   :args
   ((:name |program| :type |UInt32| :direction :in)
    (:name |uniformBlockIndex| :type |UInt32| :direction :in)
    (:name |bufSize| :type |SizeI| :direction :in)
    (:name |length| :type |SizeI| :direction :out :array t :size #x1)
    (:name |uniformBlockName| :type |Char| :direction :out :array t :size
     bufsize))
   :category "ARB_uniform_buffer_object" :deprecated nil :version "2.0")
  ("GetActiveUniformBlockiv" get-active-uniform-block-iv :return "void" :args
   ((:name |program| :type |UInt32| :direction :in)
    (:name |uniformBlockIndex| :type |UInt32| :direction :in)
    (:name |pname| :type |GLenum| :direction :in)
    (:name |params| :type |Int32| :direction :out :array t :size (|pname|)))
   :category "ARB_uniform_buffer_object" :deprecated nil :version "2.0")
  ("GetUniformBlockIndex" get-uniform-block-index :return "UInt32" :args
   ((:name |program| :type |UInt32| :direction :in)
    (:name |uniformBlockName| :type |Char| :direction :in :array t))
   :category "ARB_uniform_buffer_object" :deprecated nil :version "2.0")
  ("GetActiveUniformName" get-active-uniform-name :return "void" :args
   ((:name |program| :type |UInt32| :direction :in)
    (:name |uniformIndex| :type |UInt32| :direction :in)
    (:name |bufSize| :type |SizeI| :direction :in)
    (:name |length| :type |SizeI| :direction :out :array t :size #x1)
    (:name |uniformName| :type |Char| :direction :out :array t :size bufsize))
   :category "ARB_uniform_buffer_object" :deprecated nil :version "2.0")
  ("GetActiveUniformsiv" get-active-uniforms-iv :return "void" :args
   ((:name |program| :type |UInt32| :direction :in)
    (:name |uniformCount| :type |SizeI| :direction :in)
    (:name |uniformIndices| :type |UInt32| :direction :in :array t :size
     (|uniformCount|))
    (:name |pname| :type |GLenum| :direction :in)
    (:name |params| :type |Int32| :direction :out :array t :size (|pname|)))
   :category "ARB_uniform_buffer_object" :deprecated nil :version "2.0")
  ("GetUniformIndices" get-uniform-indices :return "void" :args
   ((:name |program| :type |UInt32| :direction :in)
    (:name |uniformCount| :type |SizeI| :direction :in)
    (:name |uniformNames| :type |CharPointer| :direction :in :array t :size
     (|uniformCount|))
    (:name |uniformIndices| :type |UInt32| :direction :out :array t :size
     (|uniformCount|)))
   :category "ARB_uniform_buffer_object" :deprecated nil :version "2.0"))) 
