;;;; This file was automatically generated by /home/bill/programming/cl-glfw/generators/make-bindings-from-spec.lisp

(in-package #:cl-glfw-opengl) 

;;;; ext_framebuffer_blit

(defconstant +read-framebuffer-ext+ #x8CA8) 
(defconstant +draw-framebuffer-ext+ #x8CA9) 
(defconstant +draw-framebuffer-binding-ext+ #x8CA6) 
(defconstant +read-framebuffer-binding-ext+ #x8CAA) 
(defconstant +read-framebuffer-ext+ #x8CA8) 
(defconstant +draw-framebuffer-ext+ #x8CA9) 
(defconstant +draw-framebuffer-binding-ext+ #x8CA6) 
(defconstant +read-framebuffer-binding-ext+ #x8CAA) 
(defglextfun "BlitFramebufferEXT" blit-framebuffer-ext :return "void" :args
 ((:name |srcX0| :type |Int32| :direction :in)
  (:name |srcY0| :type |Int32| :direction :in)
  (:name |srcX1| :type |Int32| :direction :in)
  (:name |srcY1| :type |Int32| :direction :in)
  (:name |dstX0| :type |Int32| :direction :in)
  (:name |dstY0| :type |Int32| :direction :in)
  (:name |dstX1| :type |Int32| :direction :in)
  (:name |dstY1| :type |Int32| :direction :in)
  (:name |mask| :type |ClearBufferMask| :direction :in)
  (:name |filter| :type |GLenum| :direction :in))
 :category "EXT_framebuffer_blit" :deprecated nil :version "1.5") 
(make-extension-loader |EXT_framebuffer_blit|
 (("BlitFramebufferEXT" blit-framebuffer-ext :return "void" :args
   ((:name |srcX0| :type |Int32| :direction :in)
    (:name |srcY0| :type |Int32| :direction :in)
    (:name |srcX1| :type |Int32| :direction :in)
    (:name |srcY1| :type |Int32| :direction :in)
    (:name |dstX0| :type |Int32| :direction :in)
    (:name |dstY0| :type |Int32| :direction :in)
    (:name |dstX1| :type |Int32| :direction :in)
    (:name |dstY1| :type |Int32| :direction :in)
    (:name |mask| :type |ClearBufferMask| :direction :in)
    (:name |filter| :type |GLenum| :direction :in))
   :category "EXT_framebuffer_blit" :deprecated nil :version "1.5"))) 
