;;;; This file was automatically generated by /home/bill/programming/cl-glfw/generators/make-bindings-from-spec.lisp

(in-package #:cl-glfw-opengl) 

;;;; nv_conditional_render

(defconstant +query-wait-nv+ #x8E13) 
(defconstant +query-no-wait-nv+ #x8E14) 
(defconstant +query-by-region-wait-nv+ #x8E15) 
(defconstant +query-by-region-no-wait-nv+ #x8E16) 
(defconstant +query-wait-nv+ #x8E13) 
(defconstant +query-no-wait-nv+ #x8E14) 
(defconstant +query-by-region-wait-nv+ #x8E15) 
(defconstant +query-by-region-no-wait-nv+ #x8E16) 
(defglextfun "EndConditionalRenderNV" end-conditional-render-nv :return "void"
 :args nil :category "NV_conditional_render" :deprecated nil :version nil) 
(defglextfun "BeginConditionalRenderNV" begin-conditional-render-nv :return
 "void" :args
 ((:name |id| :type |UInt32| :direction :in)
  (:name |mode| :type |TypeEnum| :direction :in))
 :category "NV_conditional_render" :deprecated nil :version nil) 
(make-extension-loader |NV_conditional_render|
 (("EndConditionalRenderNV" end-conditional-render-nv :return "void" :args nil
   :category "NV_conditional_render" :deprecated nil :version nil)
  ("BeginConditionalRenderNV" begin-conditional-render-nv :return "void" :args
   ((:name |id| :type |UInt32| :direction :in)
    (:name |mode| :type |TypeEnum| :direction :in))
   :category "NV_conditional_render" :deprecated nil :version nil))) 
