;;;; This file was automatically generated by /home/bill/programming/cl-glfw/generators/make-bindings-from-spec.lisp

(in-package #:cl-glfw-opengl) 

;;;; apple_specular_vector

(defconstant +light-model-specular-vector-apple+ #x85B0) 
(defconstant +light-model-specular-vector-apple+ #x85B0) 
