;;;; This file was automatically generated by /home/bill/programming/cl-glfw/generators/make-bindings-from-spec.lisp

(in-package #:cl-glfw-opengl) 

;;;; mesa_pack_invert

(defconstant +pack-invert-mesa+ #x8758) 
(defconstant +pack-invert-mesa+ #x8758) 
