;;;; This file was automatically generated by /home/bill/programming/cl-glfw/generators/make-bindings-from-spec.lisp

(in-package #:cl-glfw-opengl) 

;;;; nv_texture_shader2

(defconstant +dot-product-texture-3d-nv+ #x86EF) 
