;;;; This file was automatically generated by /home/bill/programming/cl-glfw/generators/make-bindings-from-spec.lisp

(in-package #:cl-glfw-opengl) 

;;;; ext_clip_volume_hint

(defconstant +clip-volume-clipping-hint-ext+ #x80F0) 
