;;;; This file was automatically generated by /home/bill/programming/cl-glfw/generators/make-bindings-from-spec.lisp

(in-package #:cl-glfw-opengl) 

;;;; arb_es2_compatibility

(defconstant +shader-binary-formats+ #x8DF8) 
(defconstant +num-shader-binary-formats+ #x8DF9) 
(defconstant +shader-compiler+ #x8DFA) 
(defconstant +max-vertex-uniform-vectors+ #x8DFB) 
(defconstant +max-varying-vectors+ #x8DFC) 
(defconstant +max-fragment-uniform-vectors+ #x8DFD) 
(defconstant +fixed+ #x140C) 
(defconstant +implementation-color-read-type+ #x8B9A) 
(defconstant +implementation-color-read-format+ #x8B9B) 
(defconstant +low-float+ #x8DF0) 
(defconstant +medium-float+ #x8DF1) 
(defconstant +high-float+ #x8DF2) 
(defconstant +low-int+ #x8DF3) 
(defconstant +medium-int+ #x8DF4) 
(defconstant +high-int+ #x8DF5) 
(defconstant +shader-compiler+ #x8DFA) 
(defconstant +num-shader-binary-formats+ #x8DF9) 
(defconstant +max-vertex-uniform-vectors+ #x8DFB) 
(defconstant +max-varying-vectors+ #x8DFC) 
(defconstant +max-fragment-uniform-vectors+ #x8DFD) 
(defglextfun "ClearDepthf" clear-depth-f :return "void" :args
 ((:name |d| :type |ClampedFloat32| :direction :in)) :category
 "ARB_ES2_compatibility" :deprecated nil :version "4.1") 
(defglextfun "DepthRangef" depth-range-f :return "void" :args
 ((:name |n| :type |ClampedFloat32| :direction :in)
  (:name |f| :type |ClampedFloat32| :direction :in))
 :category "ARB_ES2_compatibility" :deprecated nil :version "4.1") 
(defglextfun "GetShaderPrecisionFormat" get-shader-precision-format :return
 "void" :args
 ((:name |shadertype| :type |GLenum| :direction :in)
  (:name |precisiontype| :type |GLenum| :direction :in)
  (:name |range| :type |Int32| :direction :out :array t :size #x2)
  (:name |precision| :type |Int32| :direction :out :array t :size #x2))
 :category "ARB_ES2_compatibility" :deprecated nil :version "4.1") 
(defglextfun "ShaderBinary" shader-binary :return "void" :args
 ((:name |count| :type |SizeI| :direction :in)
  (:name |shaders| :type |UInt32| :direction :in :array t :size count)
  (:name |binaryformat| :type |GLenum| :direction :in)
  (:name |binary| :type |Void| :direction :in :array t :size length)
  (:name |length| :type |SizeI| :direction :in))
 :category "ARB_ES2_compatibility" :deprecated nil :version "4.1") 
(defglextfun "ReleaseShaderCompiler" release-shader-compiler :return "void"
 :args nil :category "ARB_ES2_compatibility" :deprecated nil :version "4.1") 
(make-extension-loader |ARB_ES2_compatibility|
 (("ClearDepthf" clear-depth-f :return "void" :args
   ((:name |d| :type |ClampedFloat32| :direction :in)) :category
   "ARB_ES2_compatibility" :deprecated nil :version "4.1")
  ("DepthRangef" depth-range-f :return "void" :args
   ((:name |n| :type |ClampedFloat32| :direction :in)
    (:name |f| :type |ClampedFloat32| :direction :in))
   :category "ARB_ES2_compatibility" :deprecated nil :version "4.1")
  ("GetShaderPrecisionFormat" get-shader-precision-format :return "void" :args
   ((:name |shadertype| :type |GLenum| :direction :in)
    (:name |precisiontype| :type |GLenum| :direction :in)
    (:name |range| :type |Int32| :direction :out :array t :size #x2)
    (:name |precision| :type |Int32| :direction :out :array t :size #x2))
   :category "ARB_ES2_compatibility" :deprecated nil :version "4.1")
  ("ShaderBinary" shader-binary :return "void" :args
   ((:name |count| :type |SizeI| :direction :in)
    (:name |shaders| :type |UInt32| :direction :in :array t :size count)
    (:name |binaryformat| :type |GLenum| :direction :in)
    (:name |binary| :type |Void| :direction :in :array t :size length)
    (:name |length| :type |SizeI| :direction :in))
   :category "ARB_ES2_compatibility" :deprecated nil :version "4.1")
  ("ReleaseShaderCompiler" release-shader-compiler :return "void" :args nil
   :category "ARB_ES2_compatibility" :deprecated nil :version "4.1"))) 
